# # Schema file for the configuration files of the Site Status Message module.

site_status_message.settings:
  type: config_object
  label: 'Site Status Message settings'
  mapping:
    message:
      type: text
      label: 'Status message'
    readmore:
      type: text
      label: 'More information link text'
